[project]
name = "py-wealth-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pydantic-ai>=1.37.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

